### ISSUE TITLE
CSS Problem

### ISSUE THREAD

**Issue by domesodomeso** [dulabs/Wordpress-Tabs-Slides#1]
Hi, I think there is an error in this CSS file:

/easytabs/css/easy-responsive-tabs.css 

line 2

`ul.resp-tabs-list, p {
    margin: 0px;
    padding: 0px;
}`

that komma between "ul.resp-tabs-list" and "p" causes problems with some themes because the global p style is overritten.

**Comment by dulabs** [comment]
[Already fixed for next release.](https://github.com/dulabs/Wordpress-Tabs-Slides/commit/eac8e6dc981a02bf7cc869985e88c23c7309a48b)
